# .travis.yml

sudo: required

services:
  - docker
  
before_install:
  - docker build -t andreidincu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andreidincu/docker-react npm run test -- --coverage
